In [1]:
import pandas_datareader.data as web
import os

In [2]:
#get $GME data from YAHOO
gme = web.get_data_yahoo('GME', 
                         '2020-07-01', 
                         '2021-02-15', 
                         interval='d')

gme = gme.add_prefix('GME ')

In [3]:
gme

,GME High,GME Low,GME Open,GME Close,GME Volume,GME Adj Close
Date,,,,,,
2020-07-01,4.500000,4.310000,4.310000,4.440000,2303700,4.440000
2020-07-02,4.510000,4.290000,4.490000,4.290000,1887600,4.290000
2020-07-06,4.340000,4.190000,4.310000,4.240000,2140900,4.240000
2020-07-07,4.250000,4.060000,4.200000,4.090000,2456600,4.090000
2020-07-08,4.290000,4.030000,4.100000,4.260000,2052800,4.260000
...,...,...,...,...,...,...
2021-02-08,72.660004,58.020000,72.410004,60.000000,25687300,60.000000
2021-02-09,57.000000,46.520000,56.610001,50.310001,26843100,50.310001
2021-02-10,62.830002,46.549999,50.770000,51.200001,36455000,51.200001
2021-02-11,55.320000,48.220001,50.009998,51.099998,12997400,51.099998
2021-02-12,55.240002,48.049999,50.750000,52.400002,14498000,52.400002

In [4]:
gme.plot()

In [5]:
gme.to_csv(os.path.join('data', 'gme_stock_daily.csv'))